name: MLflow CI Training & Docker

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Set up job
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Check environment
    - name: Check environment
      run: |
        python --version
        pip --version

    # 4. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas joblib

    # 5. Run MLflow Project
    - name: Run MLflow Project
      run: |
        mlflow run MLProject --env-manager=local

    # 6. Get latest MLflow run_id
    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | grep -Eo '[0-9a-f]{32}' | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"

    # 7. Upload artifacts to GitHub
    - name: Commit & Push MLflow Artifacts
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add mlruns/
        git commit -m "Add MLflow artifacts [skip ci]" || echo "No changes"
        git push origin main

    # 8. Build Docker Image from MLflow
    - name: Build Docker Model
      run: |
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name insurance_danu_model

    # 9. Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 10. Tag Docker Image
    - name: Tag Docker Image
      run: |
        docker tag insurance_danu_model \
          ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest

    # 11. Push Docker Image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/insurance_danu_model:latest